### ISSUE TITLE
Error with webpack v5

### ISSUE THREAD

**Issue by imathews** [MatthieuLemoine/unused-webpack-plugin#42]
We just updated to webpack v5, and unfortunately had to pull `unused-webpack-plugin` out of our plugins because it seems to be incompatible with the changes in v5. We're seeing the following error when including this plugin in our webpack configuration:

```
assets/node_modules/unused-files-webpack-plugin/lib/index__8.0.0__.js:105
    compiler.plugin(`after-emit`, (compilation, done) =>
             ^

TypeError: compiler.plugin is not a function
    at UnusedFilesWebpackPlugin.apply (assets/node_modules/unused-files-webpack-plugin/lib/index__8.0.0__.js:105:14)
    at createCompiler (assets/node_modules/webpack/lib/webpack.js:69:12)
    at create (assets/node_modules/webpack/lib/webpack.js:113:15)
    at webpack (assets/node_modules/webpack/lib/webpack.js:137:31)
    at f (assets/node_modules/webpack/lib/index.js:35:15)
```

**Comment by paradite** [comment]
You might want to checkout https://github.com/MQuy/webpack-deadcode-plugin
It's quite similar to this but has more features. I recently helped to add webpack 5 support to that project.

With that being said, I was able to use this project with webpack 5 as well. It should have handled the new webpack 4/5 syntax:
https://github.com/MatthieuLemoine/unused-webpack-plugin/blob/b309510e1524498422d6e4026759503d41a53940/index.js#L30-L31

**Comment by mrbalov** [comment]
Any news?
